### ISSUE TITLE
BPMN - User Interface T2P

### ISSUE THREAD

**Issue by jonastrautmann** [tfreytag/WoPeD#117]
- [x] User-Story 1.: Vorbereitung des User Interface, sodass hier ausgewählt werden kann in welchem Dateiformat das Prozessmodell erstellt wird
- [x] User-Story 2.: Splitten der Eingabe in der Methode generatePetrienetFromText sodass hier auch nur das WordModel extrahiert werden kann

- [x] User-Story 3.: erstellen einer weiteren Klasse, die die Darstellung des BPMN im User Interface übernimmt (Interpretation von Formen und Farben)
- [x] User-Story 4: erstelltes Prozessmodell downloadbar machen

**Comment by tfreytag** [comment]
Zur User story 1: Die Eingabe in den T2P-Algorithmus (Parameter der Methode) sollte nach wie vor ein String sein und nicht erweitert werden (um "alte" Versionen lauffähig zu halten). Deshalb schlage ich vor, dass für eine gewünschte BPMN-Ausgabe einfach der String "BPMN:" dem Eingabetext vorangestellt wird.
Beispiel: "BPMN: First, the employee..." 
Für PNML bleibt dann alles beim alten, d.h. von WoPeD aus funktioniert alles wie bisher ohne vorgesetzten String. 
Beim Web-Interface sollte dann ein Auswahlmenü o.ä. angeboten werden, für den Fall BPMN wird dann einfach der String "BPMN: " vor den Nutztext gehängt.

**Comment by jonastrautmann** [comment]
Der Input bleibt für beide Methoden ein String. Aktuelle Herangehensweise war dies über Radio Buttons zu lösen: 
![grafik](https://user-images.githubusercontent.com/46446573/121308352-3e29a900-c901-11eb-93ef-148ad1273de9.png)

Abhängig von der (notwendigen) Auswahl wird dann im Hintergrund entweder die Funktion aufgerufen die das Petrinetz erstellt, oder die das BPMN erstellt. Die Funktion für die Erzeugung des BPMN aus String gilt es noch zu erstellen.

**Comment by tfreytag** [comment]
Genau so sollte das aussehen. Hier noch ein ggfs. hilfreiches Dokument, wie BPMN aus dem WordlModel generiert wird, habe auch den Quellcode angefragt - allerdings nicht sicher, ob wir da rankommen.
[Dokumentation_final_rev2.pdf.download.zip](https://github.com/tfreytag/WoPeD/files/6622016/Dokumentation_final_rev2.pdf.download.zip)
Ein Frontend mit ähnlicher Funktionalität (ohne PN-Export) existiert auch schon, vermutlich mit derselben Software, die wir nutzen. http://rmm.dfki.de/index.php?site=workspace (Menüpunkt Text to BPMN Miner) 
Quellcode wohl nicht öffentlich...

**Comment by jonastrautmann** [comment]
Können Sie die Datei nochmal schicken, vielleicht in einem anderen Format ? Die Zip ist bei mir leer.

**Comment by jonastrautmann** [comment]
Da aktuell noch auf Antwort von Tom Thaler für den Code zum erstellen eines BPMN XML Strings aus dem WorldModel gewartet wird, alle anderen User Storys von diesem Epic aber bereits abgearbeitet sind, wird dies in eine andere Story geschoben, um diese hier nicht zu blockieren. Siehe https://github.com/tfreytag/WoPeD/issues/119

**Comment by jonastrautmann** [comment]
Story abgearbetiet durch @jonastrautmann
