### ISSUE TITLE
T2P - Label-Beschriftung im generierten Prozessmodell verbessern

### ISSUE THREAD

**Issue by Jannik-Steck** [tfreytag/WoPeD#87]
Bei der Verwendung von WoPeD ist aufgefallen, dass in den erstellten Prozessmodelle gelegentlich Satzzeichen mit übernommen werden und auch stellenweise mit zu vielen Informationen versehen werden. Ziel ist es, diesen Zustand zu korrigieren.

- [x] User-Story 1.: Als Nutzer von WoPeD möchte ich, dass in den Labeln in dem erstellten Prozessmodell keine Satzzeichen übernommen werden
- [x] User-Story 2.:  Als Nutzer von WoPeD möchte ich, dass die Label nur die notwendigen Informationen enthalten
- [x] User-Story 3.: Labels ragen aktuell häufig in angrenzenden Elemente rein und beinflussen die Leserlichkeit stark. Hier soll eine passende Lösung gefunden werden wie diese passend dargestellt werden können.  Beispiel: _First the manager creates a document. Then the clerk copy the document or print the document. After that the clerk send the document to the customer._
Derzeitige Ausgabe:
![grafik](https://user-images.githubusercontent.com/46446573/120317419-e1b20280-c2de-11eb-88b0-50845a16b77d.png)

**Comment by jonastrautmann** [comment]
User-Story 1.: Bei dem Satzzeichen mit in das Prozessmodell übernommen werden konnte weder mit der derzeit in WoPeD verwendeten Version des Stanfords Parser noch mit der aktuellen Version repdouziert werden. Diese Story wird geschlossen und das Epic nach Absprache als abgeschlossen angesehen. Sollte sich hier in den weiteren Sprints dieser Fehler auftreten, wird das Ticket wieder geöffnet.

**Comment by jonastrautmann** [comment]
Label Beschriftungen und Limitierung der chars angepasst durch @harunby und @jonastrautmann
