### ISSUE TITLE
T2P - Kontrollflussstrukturen verbessern (Parallelität)

### ISSUE THREAD

**Issue by jonastrautmann** [tfreytag/WoPeD#89]
Bei der Darstellung von Prozessmodellen, die Prozesse in bestimmten Reihenfolgen durchführen (beispielweise parallel) können diese häufig nicht wie gewünscht dargestellt werden. Ziel dieses Issues ist es, diesen Zustand zu beheben.

Als Nutzer von WoPeD möchte ich, dass Aspekte in der Prozessbeschreibung wie beispielsweise die Parallelität richtig von WoPeD interpretiert werden, um ein korrektes Prozessmodell darzustellen.

Nach Erweiterung der Parallelität um weitere Begriffe sollen folgende Tests durchgeführt werden

- [x] Testfall 1.: Die Verbindung zweier Sätze und die Parallelität wird richtig angezeigt. Beispiel:  _The process is registered. The history is checked and simultaneously the history is checked. Afterwards the process is finished_
Derzeitige Ausgabe: 

![grafik](https://user-images.githubusercontent.com/46446573/120208904-511be980-c22e-11eb-9865-55b2aa36183d.png)

- [x] Testfall 2.: Die Parallelität wird richtig angezeigt auch wenn die beiden Sätzen durch einen Punkt getrennt werden _The process is registered. The history is checked. Simultaneously the history is checked. Afterwards the process is finished_
Derzeitige Ausgabe:
![grafik](https://user-images.githubusercontent.com/46446573/120208806-321d5780-c22e-11eb-98c1-d2e14259503b.png)

- [x] Testfall 3.: Der Testfall stellt einen Satz da in dem mehrere Ereignisse in einer Verzweigung ausgeführt werden: _The process is registered. The history is checked then the funds are generated while the authorization is tested. The process is completed._
Derzeitige Ausgabe:
![Bildschirmfoto 2021-06-03 um 12 22 39](https://user-images.githubusercontent.com/54911105/120629905-96c2f700-c466-11eb-893c-89babda55bf0.png)

Anmerkungen: Im Laufe der Umsetzung könnte ein weiterer Testfall mit einer erhöhten Komplexität formuliert werden.

Zugewiesene Entwickler: Harun, Noah, Jonas, Jannik

**Comment by Jannik-Steck** [comment]
**User-Story 1**

Testfall:
- The process begins, when it is registered. Then, the process is split into 2 parallel branches. The fund is checked. The history is checked. After all 2 branches were executed, the process is finished.

- The process begins, when it is registered. Then, the process is split into 2 parallel branches. The fund is checked. The history is checked and the form is checked. After all 2 branches were executed, the process is finished.

Abnahme: Die Prozesse werden korrekt umgewandelt und die Parallelität richtig abgebildet. Hierbei dürfen keine Fehler oder Ungenauigkeiten auftreten.

Anmerkungen: Im Laufe der Umsetzung könnte ein weiterer Testfall mit einer erhöhten Komplexität formuliert werden.
Zugewiesene Entwickler: Harun, Noah, Jonas, Jannik

**Comment by Jannik-Steck** [comment]
**User-Story 2**

Testfall:

- When logging in, the password and username or email address are checked. If one of the two criteria does not apply, the login is denied and the user must enter his login data again. If the login is accepted the process is finished.

Abnahme: Die Prozesse werden korrekt umgewandelt und Schleifen richtig abgebildet. Hierbei dürfen keine Fehler oder Ungenauigkeiten auftreten.

Anmerkungen: Im Laufe der Umsetzung könnte ein weiterer Testfall mit einer erhöhten Komplexität formuliert werden.
Zugewiesene Entwickler: Harun, Noah, Jonas, Jannik

**Comment by jonastrautmann** [comment]
Epic des ersten Sprints, Beginn der Bearbeitung am 10.05, Review am 25.05

**Comment by jonastrautmann** [comment]
In Abstimmung wurde der Aspekt der Schleifen vorerst nach hinten verschoben und der Fokus dieser Story auf die Parallelität gelegt.

**Comment by Jannik-Steck** [comment]
Nach Recherche und Analyse im Team:
Grundproblematik ist die derzeit verwendete Stanford-Parser-Version. Idee ist hierbei die Version zu aktualisieren, was mit einem erhöhtem Aufwand (ca. ein Semester) in Verbindung steht. Der erhöhte Aufwand ist darauf zurückzuführen, dass sich die Projektstruktur im Service stark ändert (Imports/ Klassen/ Objekte/ Methoden ändern und anpassen). Gleichzeitig muss der Service weiterhin lauffähig sein.
Von dieser Aktualisierung wurde in Absprache mit Benjamin abgesehen. Sollte gegen Ende noch Zeit vorhanden sein, würde ein Konzept erstellt werden, welches sich mit der Idee befasst.

**Comment by jonastrautmann** [comment]
Stand 27.05: Eine lokale lauffähige Version besteht, die die Parallelität wie vorgesehen interpretiert und das Prozessmodell richtig erstellen kann. Hier hat Harun ein Pythonskript geschrieben, dass eine aktuellere Version des StanfordParsers (4.1.2) zur Erstellung des Baums verwendet. In Gruppenarbeit wurde dieses Skript heute in den Spring Boot Webservice eingebaut, sodass aktuell lokal eine starke Verbesserung der Parallelität erkennbar ist.

Diese Änderung wurde auch schon im Branch ControlFlowStructures übernommen. Aktuell ist diese Änderung jedoch auf anderen Geräten noch nicht lauffähig, da hier ein virtual Python Environment aufgesetzt werden muss. Hier wird in den kommenden Tagen nach einer Lösung gesucht.

**Comment by jonastrautmann** [comment]
Stand 31.05: Das Skript sind jetzt auf allen Geräten lauffähig und lässt sich ohne virtual Python Environment ausführen. Auch die Pfade sind jetzt relativ, sodass nach Klonen keine Anpassungen vorgenommen werden müssen. 

Jetzt gilt es diese Änderungen auch noch mit in die Dockerfile mit aufzunehmen, sodass dieses Skript auch im späteren produktiv-Code ausgeführt werden kann. Hierfür wurde ein extra Epic angelegt (https://github.com/tfreytag/WoPeD/issues/113)

**Comment by jonastrautmann** [comment]
Die Arbeit an diesem Epic ist als gesamte Gruppe geschehen und wurde aufgeteilt auf unterschiedliche Aspekte des Epics um dies möglichst schnell umzusetzen.
